version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      # Add other environment variables as needed
    volumes:
      - .:/usr/src/app
    command: npm start
